### ISSUE TITLE
Suggest to loosen the dependency on databases

### ISSUE THREAD

**Issue by Agnes-U** [madisvain/vatcomply#25]
Dear developers, 

Your project vatcomply requires "databases==0.5.2" in its dependency. After analyzing the source code, we found that the following versions of databases can also be suitable without affecting your project, i.e., databases 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.3, 0.5.4, 0.5.5. Therefore, we suggest to loosen the dependency on databases from "databases==0.5.2" to "databases>=0.4.0,<=0.5.5" to avoid any possible conflict for importing more packages or for downstream projects that may use ddos_script. 

May I pull a request to further loosen the dependency on databases?

By the way, could you please tell us whether such dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

<br />

----

Details: 

Your project (commit id: ce3a5bed4122c24045362b45b66bb41f7190e1ff) directly uses 1 APIs from package databases.

```
databases.core.Database.__init__
```

Beginning fromwhich, 6 functions are then indirectly called, including 3 databases's internal APIs and 3 outsider APIs as follows:
```
[/madisvain/vatcomply]
+--databases.core.Database.__init__
|      +--databases.core.DatabaseURL.__init__
|      +--databases.importer.import_from_string
|      |      +--databases.importer.ImportFromStringError.__init__
|      |      +--importlib.import_module
|      +--aiocontextvars.ContextVar
|      +--contextvars.ContextVar
```

Since all these functions have not been changed between any version for package "databases" from [0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.3, 0.5.4, 0.5.5] and 0.5.2. Therefore, we believe it is safe to loosen the corresponding dependency.

**Comment by madisvain** [comment]
@Agnes-U yes a PR is very welcome for this. The requirements could be relaxed in general I think.

**Comment by Agnes-U** [comment]
#26

**Comment by madisvain** [comment]
We have moved away from startlet to use async Django that is fast enough for the use case. Hope you find this update useful for yourself as well.
