### ISSUE TITLE
Urgent question with VATComply - The error of "MS_MAX_CONCURRENT_REQ"

### ISSUE THREAD

**Issue by HMK1512** [madisvain/vatcomply#32]
Hello Madisvain, 

I would like to explain our actual issue. 

The context is when are are checking the VAT Number (in the payment form), sometimes it is showing us the error of "MS_MAX_CONCURRENT_REQ" as attached in the image as below :  

![image_2023_09_27T13_38_36_475Z](https://github.com/madisvain/vatcomply/assets/146206863/75658a52-0083-427b-bf8e-87783ba4da01).

This is the API end point's link (https://api.vatcomply.com/) that we are using to check the VAT Number. 
Now, when we click on this link, it shows us the 404 Error. 

Therefore, we need your kind support to look into this and let us know why this issue is coming now and what can we do to resolve this because next week, we will launch our product concerning the payment module (which is included the VAT Number as important input).

Many thanks & best regards

**Comment by madisvain** [comment]
@HMK1512 very sorry for this late reply. This has been because some people abuse the free service.

I have refactored the codebase to use Async Django with Pydantic and will implement rate limiting. I will give an update before this happens and it should solve this issue as well.
